server:
  port: 8088
  servlet:
    context-path: /framework
    
spring:
  servlet:
     multipart: 
       enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#开发库
    username: root
    password: Xuan@150530
    url: jdbc:mysql://39.107.126.42:3306/face?useUnicode=true&characterEncoding=utf-8
    sql-script-encoding: UTF-8
    #最大活跃数
    maxActive: 50
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    minIdle: 1
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
　　   time-zone: GMT+8

 
mybatis:
  mapper-locations: classpath*:com/emx/platform/mapper/*Mapper.xml
  type-aliases-package: com.emx.platform.domain.*
logging:
  file: D:/interest/file/log/interest.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.interest: DEBUG
jwt:
  header: Token
  secret: w-oasis123456
  expiration: 608400
  tokenHead: ""

img:
  location: /home/files/
  
defaultValue:
  page: 1
  pageSize: 15
    
    
    
    
